#!/bin/bash
# Build all MatsyaOS packages into a local pacman repo, with proper versioning.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/pkg-version.sh
source "$SCRIPT_DIR/scripts/pkg-version.sh"

REPO_DIR="${REPO_DIR:-/home/mister/matsyaos-repo/x86_64}"
BUILD_ROOT="${BUILD_ROOT:-/tmp/matsya-build}"
MATSYA_ROOT="${MATSYA_ROOT:-$SCRIPT_DIR}"

mkdir -p "$REPO_DIR" "$BUILD_ROOT"

# Remove previous builds of the same package name so repo only keeps the new version.
remove_old_pkg() {
    local name="$1"
    find "$REPO_DIR" -maxdepth 1 -type f -name "${name}-*.pkg.tar.zst" -delete 2>/dev/null || true
}

write_pkginfo() {
    local pkg_dir="$1"
    local name="$2"
    local ver_rel="$3"   # e.g. 1.1-1
    local arch="${4:-x86_64}"
    local size
    size=$(du -sb "$pkg_dir" --exclude=.PKGINFO --exclude=.MTREE 2>/dev/null | cut -f1 || echo 0)
    cat > "$pkg_dir/.PKGINFO" << PKGINFO
# Generated by matsyaos build
pkgname = $name
pkgver = $ver_rel
pkgdesc = MatsyaOS $name package
arch = $arch
builddate = $(date +%s)
size = $size
PKGINFO
}

pack_dir() {
    local pkg_dir="$1"
    local name="$2"
    local ver_rel="$3"
    local arch="${4:-x86_64}"
    local out="$REPO_DIR/${name}-${ver_rel}-${arch}.pkg.tar.zst"

    write_pkginfo "$pkg_dir" "$name" "$ver_rel" "$arch"
    remove_old_pkg "$name"
    (
        cd "$pkg_dir"
        tar -I zstd -cf "$out" .PKGINFO $(find . -mindepth 1 -maxdepth 1 ! -name .PKGINFO -printf '%P ')
    )
    echo "==> Packaged $name ${ver_rel} -> $(basename "$out")"
}

build_cmake_pkg() {
    local name="$1"
    local dir="$2"
    local arch="${3:-x86_64}"

    if [ ! -d "$dir" ]; then
        echo "==> SKIP $name (missing $dir)"
        return 0
    fi

    local pkgver pkgrel ver_rel
    read -r pkgver pkgrel < <(resolve_pkg_version "$dir")
    ver_rel="${pkgver}-${pkgrel}"

    echo "==> Building $name $ver_rel from $dir..."

    local build_dir="$BUILD_ROOT/$name-build"
    local pkg_dir="$BUILD_ROOT/$name-pkg"
    rm -rf "$build_dir" "$pkg_dir"
    mkdir -p "$build_dir"

    # Known Qt6 fix
    if [ -f "$MATSYA_ROOT/libmatsya/mpris/mprisplayer_p.h" ]; then
        sed -i '/class QStringList;/d' "$MATSYA_ROOT/libmatsya/mpris/mprisplayer_p.h" || true
    fi

    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INCLUDE_CURRENT_DIR=ON \
          -B "$build_dir" \
          -S "$dir"

    cmake --build "$build_dir" -j"$(nproc)"
    DESTDIR="$pkg_dir" cmake --install "$build_dir"

    pack_dir "$pkg_dir" "$name" "$ver_rel" "$arch"
    rm -rf "$build_dir" "$pkg_dir"
}

pack_asset_pkg() {
    local name="$1"
    local src_dir="$2"
    local arch="${3:-x86_64}"
    local install_sub="${4:-usr/share}"

    if [ ! -d "$src_dir" ]; then
        echo "==> SKIP $name (missing $src_dir)"
        return 0
    fi

    local pkgver pkgrel ver_rel
    read -r pkgver pkgrel < <(resolve_pkg_version "$src_dir")
    ver_rel="${pkgver}-${pkgrel}"

    echo "==> Packaging $name $ver_rel..."
    local pkg_dir="$BUILD_ROOT/$name-pkg"
    rm -rf "$pkg_dir"
    mkdir -p "$pkg_dir/$install_sub"
    cp -a "$src_dir"/. "$pkg_dir/$install_sub/" 2>/dev/null || \
        cp -r "$src_dir"/* "$pkg_dir/$install_sub/" 2>/dev/null || true

    pack_dir "$pkg_dir" "$name" "$ver_rel" "$arch"
    rm -rf "$pkg_dir"
}

echo "============================================"
echo "MatsyaOS package build"
echo "Default release: ${MATSYA_DEFAULT_PKGVER}-${MATSYA_DEFAULT_PKGREL}"
echo "Output repo:     $REPO_DIR"
echo "============================================"

# Foundation
build_cmake_pkg "libmatsya"            "$MATSYA_ROOT/libmatsya"
build_cmake_pkg "matsyaui"             "$MATSYA_ROOT/matsyaui"

# Core system
build_cmake_pkg "matsya-daemon"        "$MATSYA_ROOT/daemon"
build_cmake_pkg "matsya-core"          "$MATSYA_ROOT/core"
build_cmake_pkg "matsya-kwin-plugins"  "$MATSYA_ROOT/kwin-plugins"
build_cmake_pkg "matsya-screenlocker"  "$MATSYA_ROOT/screenlocker"

# Desktop shell
build_cmake_pkg "matsya-launcher"      "$MATSYA_ROOT/launcher"
build_cmake_pkg "matsya-dock"          "$MATSYA_ROOT/dock"
build_cmake_pkg "matsya-statusbar"     "$MATSYA_ROOT/statusbar"
build_cmake_pkg "matsya-appmotor"      "$MATSYA_ROOT/appmotor"

# Applications
build_cmake_pkg "matsya-calculator"    "$MATSYA_ROOT/calculator"
build_cmake_pkg "matsya-terminal"      "$MATSYA_ROOT/terminal"
build_cmake_pkg "matsya-texteditor"    "$MATSYA_ROOT/texteditor"
build_cmake_pkg "matsya-filemanager"   "$MATSYA_ROOT/filemanager"
build_cmake_pkg "matsya-screenshot"    "$MATSYA_ROOT/screenshot"
build_cmake_pkg "matsya-settings"      "$MATSYA_ROOT/matsya-settings"
build_cmake_pkg "matsya-qt-plugins"    "$MATSYA_ROOT/qt-plugins"
build_cmake_pkg "matsya-sddm-theme"    "$MATSYA_ROOT/sddm-theme"

# Optional (may be absent)
build_cmake_pkg "matsya-debinstaller"  "$MATSYA_ROOT/debinstaller"
build_cmake_pkg "matsya-updater"       "$MATSYA_ROOT/matsya-updater"

# Asset / data packages (use cmake to ensure proper install destination)
build_cmake_pkg "matsya-icons"          "$MATSYA_ROOT/icons"
build_cmake_pkg "matsya-gtk-themes"     "$MATSYA_ROOT/gtk-themes"
build_cmake_pkg "matsya-wallpappers"    "$MATSYA_ROOT/wallpappers"

# Namaste welcome app (data layout differs)
if [ -d "$MATSYA_ROOT/matsya-namaste" ]; then
    name="matsya-namaste"
    read -r pkgver pkgrel < <(resolve_pkg_version "$MATSYA_ROOT/matsya-namaste")
    ver_rel="${pkgver}-${pkgrel}"
    echo "==> Packaging $name $ver_rel..."
    pkg_dir="$BUILD_ROOT/$name-pkg"
    rm -rf "$pkg_dir"
    mkdir -p "$pkg_dir/usr/share/matsya" \
             "$pkg_dir/etc/xdg/autostart" \
             "$pkg_dir/usr/share/applications" \
             "$pkg_dir/usr/share/icons/hicolor/64x64/apps" \
             "$pkg_dir/usr/share/licenses/$name" \
             "$pkg_dir/usr/share/doc/$name"
    cp -r "$MATSYA_ROOT/matsya-namaste/data/." "$pkg_dir/usr/share/matsya/" 2>/dev/null || true
    [ -f "$MATSYA_ROOT/matsya-namaste/data/Welcome.desktop" ] && \
        cp "$MATSYA_ROOT/matsya-namaste/data/Welcome.desktop" "$pkg_dir/etc/xdg/autostart/" && \
        cp "$MATSYA_ROOT/matsya-namaste/data/Welcome.desktop" "$pkg_dir/usr/share/applications/"
    [ -f "$MATSYA_ROOT/matsya-namaste/data/matsya.svg" ] && \
        install -Dm644 "$MATSYA_ROOT/matsya-namaste/data/matsya.svg" \
            "$pkg_dir/usr/share/icons/hicolor/64x64/apps/matsya.svg"
    [ -f "$MATSYA_ROOT/matsya-namaste/LICENSE" ] && \
        install -Dm644 "$MATSYA_ROOT/matsya-namaste/LICENSE" "$pkg_dir/usr/share/licenses/$name/LICENSE"
    [ -f "$MATSYA_ROOT/matsya-namaste/README.md" ] && \
        install -Dm644 "$MATSYA_ROOT/matsya-namaste/README.md" "$pkg_dir/usr/share/doc/$name/README.md"
    pack_dir "$pkg_dir" "$name" "$ver_rel" "any"
    rm -rf "$pkg_dir"
fi

# Plymouth theme
if [ -d "$MATSYA_ROOT/plymouth-theme-matsya" ]; then
    name="matsya-plymouth-theme"
    read -r pkgver pkgrel < <(resolve_pkg_version "$MATSYA_ROOT/plymouth-theme-matsya")
    ver_rel="${pkgver}-${pkgrel}"
    echo "==> Packaging $name $ver_rel..."
    pkg_dir="$BUILD_ROOT/$name-pkg"
    rm -rf "$pkg_dir"
    theme_dir="$pkg_dir/usr/share/plymouth/themes/matsya-plymouth"
    mkdir -p "$theme_dir" "$pkg_dir/usr/share/licenses/$name"
    cp "$MATSYA_ROOT/plymouth-theme-matsya"/image-*.png "$theme_dir/" 2>/dev/null || true
    cp "$MATSYA_ROOT/plymouth-theme-matsya/matsya-plymouth.plymouth" "$theme_dir/" 2>/dev/null || true
    cp "$MATSYA_ROOT/plymouth-theme-matsya/matsya-plymouth.script" "$theme_dir/" 2>/dev/null || true
    [ -f "$MATSYA_ROOT/plymouth-theme-matsya/LICENSE" ] && \
        install -Dm644 "$MATSYA_ROOT/plymouth-theme-matsya/LICENSE" "$pkg_dir/usr/share/licenses/$name/LICENSE"
    pack_dir "$pkg_dir" "$name" "$ver_rel" "any"
    rm -rf "$pkg_dir"
fi

# GRUB theme
if [ -d "$MATSYA_ROOT/matsyaos-grub-theme" ]; then
    name="matsyaos-grub-theme"
    read -r pkgver pkgrel < <(resolve_pkg_version "$MATSYA_ROOT/matsyaos-grub-theme")
    ver_rel="${pkgver}-${pkgrel}"
    echo "==> Packaging $name $ver_rel..."
    pkg_dir="$BUILD_ROOT/$name-pkg"
    rm -rf "$pkg_dir"
    mkdir -p "$pkg_dir/usr/share/grub/themes" "$pkg_dir/usr/share/licenses/$name"
    # Prefer packaged theme tree if present
    if [ -d "$MATSYA_ROOT/matsyaos-grub-theme/matsya" ]; then
        cp -a "$MATSYA_ROOT/matsyaos-grub-theme/matsya" "$pkg_dir/usr/share/grub/themes/"
    else
        cp -a "$MATSYA_ROOT/matsyaos-grub-theme" "$pkg_dir/usr/share/grub/themes/matsya" 2>/dev/null || true
    fi
    [ -f "$MATSYA_ROOT/matsyaos-grub-theme/LICENSE" ] && \
        install -Dm644 "$MATSYA_ROOT/matsyaos-grub-theme/LICENSE" "$pkg_dir/usr/share/licenses/$name/LICENSE"
    pack_dir "$pkg_dir" "$name" "$ver_rel" "any"
    rm -rf "$pkg_dir"
fi

# Rebuild pacman database
cd "$REPO_DIR"
rm -f matsyaos.db matsyaos.db.tar.gz matsyaos.files matsyaos.files.tar.gz \
      matsyaos.db.tar.gz.old matsyaos.files.tar.gz.old 2>/dev/null || true
repo-add matsyaos.db.tar.gz ./*.pkg.tar.zst
# repo-add leaves symlinks; materialize for GitHub raw hosting
for link in matsyaos.db matsyaos.files; do
    if [ -L "$link" ]; then
        target=$(readlink "$link")
        rm -f "$link"
        cp -a "$target" "$link"
    fi
done

echo ""
echo "============================================"
echo "All packages built and repo database updated"
echo "Packages in: $REPO_DIR"
echo "Versions:"
ls -1 "$REPO_DIR"/*.pkg.tar.zst 2>/dev/null | xargs -n1 basename
echo "============================================"
