#!/bin/bash
set -e

CONTAINER_NAME="matsyaos-builder"
IMAGE_NAME="localhost/matsyaos-builder:latest"

echo "=== Building MatsyaOS Build Container ==="

# Create the Containerfile
cat > /tmp/Containerfile.build << 'EOF'
FROM archlinux:latest

# Install core build deps
RUN pacman -Syu --noconfirm && \
    pacman -S --needed --noconfirm \
        base-devel git cmake extra-cmake-modules ninja pkgconf \
        qt6-base qt6-declarative qt6-tools qt6-svg qt6-sensors qt6-shadertools \
        bluez-qt \
        kconfig kconfigwidgets kcoreaddons kguiaddons kwindowsystem kwayland \
        kdecoration kio kidletime kdeclarative kwin solid \
        syntax-highlighting \
        networkmanager-qt modemmanager-qt \
        kscreen qqc2-desktop-style taglib \
        polkit polkit-qt6 \
        libkscreen libqtxdg libdbusmenu-lxqt \
        accountsservice \
        freetype2 fontconfig \
        libxcursor libpulse libxcb libxtst \
        xorg-server-devel xf86-input-libinput xf86-input-synaptics \
        archiso arch-install-scripts \
        openssh rsync sudo && \
    pacman -Scc --noconfirm

# Create build user
RUN useradd -m -G wheel builder && \
    echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /workspace
EOF

echo "Building container image..."
podman build -t "$IMAGE_NAME" -f /tmp/Containerfile.build /tmp

echo "=== Running build inside container ==="

# Mount MatsyaOS repos and run the build
podman run --rm --replace --name "$CONTAINER_NAME" \
    -v /home/mister/MatsyaOS:/workspace/MatsyaOS:z \
    -v /home/mister/matsyaos-repo:/workspace/repo:z \
    "$IMAGE_NAME" \
    /bin/bash -c '
cd /workspace/MatsyaOS

REPO_DIR="/workspace/repo/x86_64"
mkdir -p "$REPO_DIR"

build_pkg() {
    local name="$1"
    local dir="$2"
    local pkgver="${3:-1.0}"
    echo "==> Building $name from $dir..."
    local bdir="/tmp/build-$name"
    local pdir="/tmp/pkg-$name"
    rm -rf "$bdir" "$pdir"
    mkdir -p "$bdir"

    # Patch Qt6 QStringList issue in libmatsya
    if [ -f "$dir/../libmatsya/mpris/mprisplayer_p.h" ]; then
        sed -i "/class QStringList;/d" "$dir/../libmatsya/mpris/mprisplayer_p.h"
    fi

    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INCLUDE_CURRENT_DIR=ON \
          -B "$bdir" -S "$dir" 2>&1 || {
        echo "FAILED: $name cmake configure"
        return 1
    }
    cmake --build "$bdir" -j$(nproc) 2>&1 || {
        echo "FAILED: $name cmake build"
        return 1
    }
    DESTDIR="$pdir" cmake --install "$bdir" 2>&1 || {
        echo "FAILED: $name cmake install"
        return 1
    }

    # Create .PKGINFO for valid pacman package
    cat > "$pdir/.PKGINFO" << PKGINFO
# Generated by matsyaos build
pkgname = $name
pkgver = $pkgver-1
pkgdesc = MatsyaOS $name package
arch = x86_64
builddate = $(date +%s)
size = $(du -sb "$pdir" --exclude=.PKGINFO 2>/dev/null | cut -f1)
PKGINFO

    cd "$pdir"
    tar -czf "$REPO_DIR/$name-${pkgver}-1-x86_64.pkg.tar.zst" .PKGINFO *
    cd /workspace
    rm -rf "$bdir" "$pdir"
    echo "==> $name built and packaged"
    return 0
}

# Build in dependency order
# Foundation
build_pkg "libmatsya" "/workspace/MatsyaOS/libmatsya"
build_pkg "matsyaui" "/workspace/MatsyaOS/matsyaui"

# Core system
build_pkg "matsya-daemon" "/workspace/MatsyaOS/daemon"
build_pkg "matsya-core" "/workspace/MatsyaOS/core"
build_pkg "matsya-kwin-plugins" "/workspace/MatsyaOS/kwin-plugins"
build_pkg "matsya-screenlocker" "/workspace/MatsyaOS/screenlocker"

# Desktop components
build_pkg "matsya-launcher" "/workspace/MatsyaOS/launcher"
build_pkg "matsya-dock" "/workspace/MatsyaOS/dock"
build_pkg "matsya-statusbar" "/workspace/MatsyaOS/statusbar"
build_pkg "matsya-appmotor" "/workspace/MatsyaOS/appmotor"

# Applications
build_pkg "matsya-calculator" "/workspace/MatsyaOS/calculator"
build_pkg "matsya-terminal" "/workspace/MatsyaOS/terminal"
build_pkg "matsya-texteditor" "/workspace/MatsyaOS/texteditor"
build_pkg "matsya-filemanager" "/workspace/MatsyaOS/filemanager"
build_pkg "matsya-screenshot" "/workspace/MatsyaOS/screenshot"
build_pkg "matsya-debinstaller" "/workspace/MatsyaOS/debinstaller"
build_pkg "matsya-settings" "/workspace/MatsyaOS/matsya-settings"
build_pkg "matsya-updater" "/workspace/MatsyaOS/matsya-updater"
build_pkg "matsya-qt-plugins" "/workspace/MatsyaOS/qt-plugins"
build_pkg "matsya-sddm-theme" "/workspace/MatsyaOS/sddm-theme"

# Asset packages (no build, just packaging)
for asset in icons gtk-themes wallpappers; do
    echo "==> Packaging matsya-$asset..."
    pdir="/tmp/pkg-matsya-$asset"
    rm -rf "$pdir"
    mkdir -p "$pdir/usr/share"
    cp -r "/workspace/MatsyaOS/$asset"/* "$pdir/usr/share/" 2>/dev/null || true
    cat > "$pdir/.PKGINFO" << PKGINFO
# Generated by matsyaos build
pkgname = matsya-$asset
pkgver = 1.0-1
pkgdesc = MatsyaOS $asset assets
arch = x86_64
builddate = $(date +%s)
size = $(du -sb "$pdir" --exclude=.PKGINFO 2>/dev/null | cut -f1)
PKGINFO
    cd "$pdir"
    tar -czf "$REPO_DIR/matsya-$asset-1.0-1-x86_64.pkg.tar.zst" .PKGINFO *
    cd /workspace
    rm -rf "$pdir"
    echo "==> matsya-$asset packaged"
done

# Create pacman database
cd "$REPO_DIR"
repo-add matsyaos.db.tar.gz *.pkg.tar.zst
echo "=== ALL PACKAGES BUILT SUCCESSFULLY ==="
ls -lh "$REPO_DIR/"
'

echo "=== Build complete! Packages in /home/mister/matsyaos-repo/x86_64/ ==="
