#!/bin/bash
# Re-stamp existing .pkg.tar.zst files with updated pkgver from PKGBUILDs / default release.
# Use when binaries are already built but versions are still stuck at 1.0-1.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MATSYA_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=pkg-version.sh
source "$SCRIPT_DIR/pkg-version.sh"

REPO_DIR="${REPO_DIR:-/home/mister/matsyaos-repo/x86_64}"
WORK="${WORK:-/tmp/matsya-reversion}"
mkdir -p "$REPO_DIR" "$WORK"

# Map pacman package name -> source directory (for PKGBUILD lookup)
declare -A PKG_DIRS=(
    [libmatsya]="$MATSYA_ROOT/libmatsya"
    [matsyaui]="$MATSYA_ROOT/matsyaui"
    [matsya-daemon]="$MATSYA_ROOT/daemon"
    [matsya-core]="$MATSYA_ROOT/core"
    [matsya-kwin-plugins]="$MATSYA_ROOT/kwin-plugins"
    [matsya-screenlocker]="$MATSYA_ROOT/screenlocker"
    [matsya-launcher]="$MATSYA_ROOT/launcher"
    [matsya-dock]="$MATSYA_ROOT/dock"
    [matsya-statusbar]="$MATSYA_ROOT/statusbar"
    [matsya-appmotor]="$MATSYA_ROOT/appmotor"
    [matsya-calculator]="$MATSYA_ROOT/calculator"
    [matsya-terminal]="$MATSYA_ROOT/terminal"
    [matsya-texteditor]="$MATSYA_ROOT/texteditor"
    [matsya-filemanager]="$MATSYA_ROOT/filemanager"
    [matsya-screenshot]="$MATSYA_ROOT/screenshot"
    [matsya-settings]="$MATSYA_ROOT/matsya-settings"
    [matsya-qt-plugins]="$MATSYA_ROOT/qt-plugins"
    [matsya-sddm-theme]="$MATSYA_ROOT/sddm-theme"
    [matsya-icons]="$MATSYA_ROOT/icons"
    [matsya-gtk-themes]="$MATSYA_ROOT/gtk-themes"
    [matsya-wallpappers]="$MATSYA_ROOT/wallpappers"
    [matsya-namaste]="$MATSYA_ROOT/matsya-namaste"
    [matsya-plymouth-theme]="$MATSYA_ROOT/plymouth-theme-matsya"
    [matsyaos-grub-theme]="$MATSYA_ROOT/matsyaos-grub-theme"
    [matsya-updater]="$MATSYA_ROOT/matsya-updater"
    [matsya-debinstaller]="$MATSYA_ROOT/debinstaller"
)

# Parse name and arch from filename: name-ver-rel-arch.pkg.tar.zst
# Ver can contain dots; arch is x86_64 or any.
parse_pkg_file() {
    local base="$1"
    base="${base%.pkg.tar.zst}"
    if [[ "$base" =~ ^(.+)-([^-]+)-([0-9]+)-(x86_64|any)$ ]]; then
        PKG_NAME="${BASH_REMATCH[1]}"
        OLD_VER="${BASH_REMATCH[2]}"
        OLD_REL="${BASH_REMATCH[3]}"
        PKG_ARCH="${BASH_REMATCH[4]}"
        return 0
    fi
    return 1
}

echo "=== Reversioning packages in $REPO_DIR ==="
echo "Default release: ${MATSYA_DEFAULT_PKGVER}-${MATSYA_DEFAULT_PKGREL}"

shopt -s nullglob
for pkgfile in "$REPO_DIR"/*.pkg.tar.zst; do
    base=$(basename "$pkgfile")
    if ! parse_pkg_file "$base"; then
        echo "SKIP (unparsed): $base"
        continue
    fi

    src_dir="${PKG_DIRS[$PKG_NAME]:-}"
    if [ -n "$src_dir" ] && [ -d "$src_dir" ]; then
        read -r new_ver new_rel < <(resolve_pkg_version "$src_dir")
    else
        # Keep special versions (e.g. namaste 23.01, grub 3.4) if already higher
        if [[ "$OLD_VER" =~ ^[0-9]+(\.[0-9]+)+$ ]] && \
           [[ "$OLD_VER" != "1.0" && "$OLD_VER" != "1" && "$OLD_VER" != "0.7" ]]; then
            new_ver="$OLD_VER"
            new_rel="$OLD_REL"
        else
            new_ver="$MATSYA_DEFAULT_PKGVER"
            new_rel="$MATSYA_DEFAULT_PKGREL"
        fi
    fi

    new_ver_rel="${new_ver}-${new_rel}"
    old_ver_rel="${OLD_VER}-${OLD_REL}"
    new_name="${PKG_NAME}-${new_ver_rel}-${PKG_ARCH}.pkg.tar.zst"
    new_path="$REPO_DIR/$new_name"

    if [ "$base" = "$new_name" ]; then
        echo "OK (already current): $base"
        continue
    fi

    echo "UPGRADE $PKG_NAME: $old_ver_rel -> $new_ver_rel"

    extr="$WORK/$PKG_NAME"
    rm -rf "$extr"
    mkdir -p "$extr"
    tar -I zstd -xf "$pkgfile" -C "$extr"

    # Update .PKGINFO
    if [ -f "$extr/.PKGINFO" ]; then
        sed -i -E "s/^pkgver = .*/pkgver = ${new_ver_rel}/" "$extr/.PKGINFO"
        sed -i -E "s/^pkgname = .*/pkgname = ${PKG_NAME}/" "$extr/.PKGINFO"
        # refresh builddate
        sed -i -E "s/^builddate = .*/builddate = $(date +%s)/" "$extr/.PKGINFO"
    else
        size=$(du -sb "$extr" --exclude=.PKGINFO 2>/dev/null | cut -f1 || echo 0)
        cat > "$extr/.PKGINFO" << PKGINFO
# Generated by matsyaos reversion
pkgname = $PKG_NAME
pkgver = $new_ver_rel
pkgdesc = MatsyaOS $PKG_NAME package
arch = $PKG_ARCH
builddate = $(date +%s)
size = $size
PKGINFO
    fi

    (
        cd "$extr"
        # Drop old .MTREE if present (hashes would be stale); pacman tolerates absence with Optional sig
        rm -f .MTREE
        tar -I zstd -cf "$new_path" .PKGINFO $(find . -mindepth 1 -maxdepth 1 ! -name .PKGINFO -printf '%P ')
    )

    # Remove old file if different path
    if [ "$pkgfile" != "$new_path" ]; then
        rm -f "$pkgfile"
    fi
    rm -rf "$extr"
    echo "  -> $new_name"
done

echo "=== Rebuilding repo database ==="
cd "$REPO_DIR"
rm -f matsyaos.db matsyaos.db.tar.gz matsyaos.files matsyaos.files.tar.gz \
      matsyaos.db.tar.gz.old matsyaos.files.tar.gz.old 2>/dev/null || true
repo-add matsyaos.db.tar.gz ./*.pkg.tar.zst
for link in matsyaos.db matsyaos.files; do
    if [ -L "$link" ]; then
        target=$(readlink "$link")
        rm -f "$link"
        cp -a "$target" "$link"
    fi
done

echo "=== Done. Current packages: ==="
ls -1 "$REPO_DIR"/*.pkg.tar.zst | xargs -n1 basename
